export const USER_LOGING_REQUEST = 'USER_LOGING_REQUEST';
export const USER_LOGING_SUCCESS = 'USER_LOGING_SUCCESS';
export const USER_LOGING_FAIL = 'USER_LOGING_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
